web_scraping:
  start_page: https://books.toscrape.com/
  product_name_selector: "h3 > a"
  product_price_selector: ".price_color"
  product_description_selector: "#product_description ~ p"
  product_image_selector: ".item.active img"
